"""creation tables initiales

Revision ID: 0536e2fd75a2
Revises: 
Create Date: 2026-07-09 14:45:38.536069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0536e2fd75a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.Enum('equipement_type', 'machine', name='scopetype'), nullable=False),
    sa.Column('scope_id', sa.String(length=50), nullable=False),
    sa.Column('parametre', sa.Enum('probabilite_panne', 'temperature', 'vitesse', 'couple', name='parametre'), nullable=False),
    sa.Column('seuil_surveillance', sa.Float(), nullable=False),
    sa.Column('seuil_maintenance', sa.Float(), nullable=False),
    sa.Column('seuil_critique', sa.Float(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_thresholds_id'), 'alert_thresholds', ['id'], unique=False)
    op.create_index(op.f('ix_alert_thresholds_scope_id'), 'alert_thresholds', ['scope_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('code_CIN', sa.String(length=20), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_code_CIN'), 'users', ['code_CIN'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nom'), 'users', ['nom'], unique=False)
    op.create_index(op.f('ix_users_prenom'), 'users', ['prenom'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('type_equipement', sa.String(length=50), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.Column('statut_operationnel', sa.Enum('production', 'arret_planifie', 'maintenance', 'hors_service', name='statutoperationnel'), nullable=True),
    sa.Column('technicien_id', sa.Integer(), nullable=True),
    sa.Column('date_installation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['technicien_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_type_equipement'), 'machines', ['type_equipement'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('reading_timestamp', sa.DateTime(), nullable=False),
    sa.Column('reading_machine_id', sa.Integer(), nullable=False),
    sa.Column('probabilite', sa.Float(), nullable=False),
    sa.Column('modele_version', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_machine_id'), 'predictions', ['machine_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('vitesse', sa.Float(), nullable=False),
    sa.Column('couple', sa.Float(), nullable=False),
    sa.Column('usure_min', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('machine_id', 'timestamp')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('parametre_declencheur', sa.String(length=50), nullable=False),
    sa.Column('valeur_mesuree', sa.Float(), nullable=False),
    sa.Column('seuil_depasse', sa.Float(), nullable=False),
    sa.Column('niveau', sa.Enum('normal', 'surveillance', 'maintenance', 'critique', name='niveaualerte'), nullable=False),
    sa.Column('statut', sa.Enum('ouverte', 'fermee', name='statutalert'), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_fermeture', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_machine_id'), 'alerts', ['machine_id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.Enum('en_cours', 'terminee', 'annulee', name='statutintervention'), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['technicien_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_alert_id'), 'interventions', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interventions_alert_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_alerts_machine_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_predictions_machine_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_machines_type_equipement'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_users_prenom'), table_name='users')
    op.drop_index(op.f('ix_users_nom'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_code_CIN'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_alert_thresholds_scope_id'), table_name='alert_thresholds')
    op.drop_index(op.f('ix_alert_thresholds_id'), table_name='alert_thresholds')
    op.drop_table('alert_thresholds')
    # ### end Alembic commands ###
