"""code_CIN obligatoire

Revision ID: feebe536a3c1
Revises: 88f51bae0ed4
Create Date: 2026-07-11 21:48:15.435329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feebe536a3c1'
down_revision: Union[str, Sequence[str], None] = '88f51bae0ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('sensor_readings_timestamp_idx'), table_name='sensor_readings')
    op.alter_column('users', 'code_CIN',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'code_CIN',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('sensor_readings_timestamp_idx'), 'sensor_readings', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
